sprint-1/step-2.
tyumen-777/react-burger pull request #2
Opened 2022-05-25 17:54 UTC by tyumen-777

sprint-1/step-2. feat: сверстать два новых компонента. подключить к апи.

2022-05-25 19:36 UTC, kyzinatra commented on src/components/App/App.tsx
> +  const [ingredients, setIngredients] = useState([]);
Можно лучше: Стейт ингредиентов также стоит типизировать

2022-05-25 19:37 UTC, kyzinatra commented on src/components/App/App.tsx
> +      setIngredients(data.data);
Надо исправить: Стоит добавить проверку успешности выполнения с помощью `res.ok` так как `catch` ловит только ошибки в самом запросе, но если сервер вернет в кримеру ошибку `404`, то ее `catch` не поймает.

[Подробнее:](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch) ([https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch))

2022-05-25 19:37 UTC, kyzinatra commented on src/components/App/App.tsx
> +      const data = await res.json();
Можно лучше: стоит типизировать тот обьект, что вернет нам res.json

2022-05-25 19:39 UTC, kyzinatra commented on src/components/App/App.tsx
> +    setIngredientDetails(ingredientDetails);
Можно лучше: Если вы решили использовать typescript, то рекомендую не оставлять пустых типов по возможности так как это несет много проблем в будущем и по сути лишает ts смысла, только мешать будет

2022-05-25 19:40 UTC, kyzinatra commented on src/components/Modal/Modal.tsx
> +        <div className={`${styles.title_wrapper} mt-10 ml-10 mr-10`}>
Надо исправить: вместо того, чтобы открывать модальное окно по условию в нем самом лучше сделать условный рендер в компоненте где `Modal` вызывается (у вас `app.tsx`)

2022-05-25 19:41 UTC, kyzinatra commented on src/components/Modal/Modal.tsx
> +  }, [onEscapeClose]);
Отлично! Круто, что вы очищаете обработчик после демонтирования компонента

2022-05-25 19:47 UTC, kyzinatra commented on src/components/BurgerIngredient/BurgerIngredient.tsx
> +  const handleOpenModal = () => {
Вместо этой длинной нотации с типами можете использовать
```js
import React, {FC} from "react"

const Component: FC<IComponent> = () => {}

```

2022-05-25 19:49 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
>          <h2 className="text text_type_main-medium mt-10 mb-6">Булки</h2>
Можно лучше: будет здорово выглядеть если по клику на таб список будет прокручиваться к нужному месту. Это можно сделать с помощью `element.scrollIntoView({ behavior: "smooth" });`

Подробнее: https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2022-05-25 19:50 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>            <p className="text text_type_digits-medium mr-2">610</p>
Надо исправить: Название булки и ее цена также должны браться из входящих данных так как в будущем эта информация будет меняться

2022-05-25 19:54 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>            <CurrencyIcon type="primary" />
Надо исправить: При генерации элементов конструктора не стоит указывать `id` конкретного ингредиента так как в конструкторе может быть несколько элементов одного типа. В будущем вы будете самостоятельно генерировать уникальный `id` для каждого элемента конструктора, а пока можете использова `index` массива

2022-05-25 19:57 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
>  }
Можно лучше: по аналогии лучше не использовать `any`

2022-05-25 20:02 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- В компоненте `AppHeader.tsx` стоит обернуть ссылки и иконки для них в соответствующий тэг `<a>`. В будущем вы будете использовать для этого `Link` из `react-router`, а пока сделайте так. 
-  Добавить проверку `res.ok`
- В конструкторе булки также стоит брать из входящих данных
- При генерации элементов конструктора не использовать `id` элемента

Можно лучше:

- Папку `.idea` лучше вынести в `.gitignore` так как она не влиянет на запуск или сборку проекта, а является полностью локальной.
- файл `data.js` не используется, его можно убрать
- Поработать над типизацией `any`

Что понравилось:

- Код написан аккуратно
- Мне понравилось, что вы правильно используете все хуки и очищаете обработчики

2022-05-26 16:11 UTC, tyumen-777 commented on src/components/BurgerIngredient/BurgerIngredient.tsx
> +  const handleOpenModal = () => {
Я слышал что такой подход считается не очень хорошим. Про этот Абрамов писал где то на гитхабе.

2022-05-26 16:37 UTC, kyzinatra commented on src/components/BurgerIngredient/BurgerIngredient.tsx
> +  const handleOpenModal = () => {
Да, вы правы многие программисты предпочитают указывать пропал вот так:
```js
const BurgerIngredient = ({ data }: IBurgerIngredientProps) => {} // обратите внимание что указывать что возвращается не обязательно. Ts сам это опредедит
```
Но тут очень тонкие различия, а именно в неявном объявлении children и проблем с defaultprops и хоть в react 18 с этим частично разобрались (хотя не полностью) всё ещё очень спорная тема, однако по моему опыту в реальных проектах чаще используется моя нотация просто как более понятная. Однако вы правы и если для вашего компонента принципиально, чтобы children был к примеру объявлен явно, то можно поступить как вы сделали. Мой комментарий скорее написан исходя из личного опыта. Так как на практике часто эти проблемы не существенны для большинства компонентов

2022-05-26 16:40 UTC, tyumen-777 commented on src/components/BurgerIngredient/BurgerIngredient.tsx
> +  const handleOpenModal = () => {
Спасибо большое! Буду знать. Мне и самому такой подход больше нравится. Где я сейчас работаю, пишут именно как вы указали...

2022-05-26 16:43 UTC, kyzinatra commented on src/components/BurgerIngredient/BurgerIngredient.tsx
> +  const handleOpenModal = () => {
Если вам больше нравится обычный способ объявления, то оставьте его. Плохого вам точно никто не скажет)

2022-05-26 18:29 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>        </div>
Надо исправить: не совсем корректна создание булок. Булка берется из api верно, но цена также статична, нет текстого указания, что булка верхняя, а также нижняя булка все также статична. Стоит сделать примерно вот так
```js
<ConstructorElement
          text={`${bun.name} (верх/них)`}
          thumbnail={data[0].image}
          price={bun.price}
          type="bottom"
          isLocked
        />
```

2022-05-26 18:33 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>          </div>
Надо исправить: также заметил, что у вас немного не верно генерируется, прошу прощения что в первый раз проглядел.  Ее стоит считать исходя из всех ингредиентов. Примерно так
```js
const price = useMemo(() => data.filter(/*исключим bun*/).reduce(() => /*считаем общую цену*/, bun.rpice*2), [data])
```

2022-05-26 18:35 UTC, kyzinatra requested changes
Почти все ошибки исправленны корретно. Осталось чуть-чуть подредактировать constructor

2022-05-27 08:13 UTC, kyzinatra commented
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2022-05-31 18:48 UTC, merged