sprint-2/step-2.
tyumen-777/react-burger pull request #4
Opened 2022-06-14 06:53 UTC by tyumen-777

feat: реализовать функционал перетаскивания ингредиентов. подключить проект к редакс

2022-06-14 14:44 UTC, kyzinatra commented on src/services/reducers/index.ts
> +  constructorOfOrder: getConstructorIngredientReducer,
Можно лучше: Стоит разбить отдельные редьюсеры в разные файлы и просто импортировать их сюда

2022-06-14 14:45 UTC, kyzinatra commented on package.json
>      "@testing-library/jest-dom": "5.16.4",
Можно лучше: если не используете `@reduxjs/toolkit`, то лучше удалить его из зависимостей

2022-06-14 15:06 UTC, kyzinatra commented on src/services/reducers/index.ts
> +        orderRequest: true,
Надо исправить: по смыслу приставка `GET_` обозначает какое-то получение. Тут по смыслу больше подойдет `SET` или `SEND`. В редуксе вообще практически не используются приставки IS HAS GET

2022-06-14 15:09 UTC, kyzinatra commented on src/services/actions/index.ts
> +          type: GET_ORDER_FAILED,
Надо исправить: после неудачного запроса стоит очищать состояние модального окна, чтобы пользователь не мог увидеть старое состояние

2022-06-14 15:13 UTC, kyzinatra commented on src/services/store.ts
> +    ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
Можно лучше: Чтобы devtools не подключались в продакшене стоит проверять process.env.NODE_ENV === "devolopment"

2022-06-14 15:15 UTC, kyzinatra commented on src/components/App/App.tsx
> +  const ingredientsRequest = useSelector((store: any) => store.burgerIngredients.ingredientsRequest);
Можно лучше: Если вы используете ts, то необходимо типизировать все ``redux` хуки. Сейчас это не является ошибкой, но в будущих спринтах, посто прохождения ts это будет обязательно

2022-06-14 15:19 UTC, kyzinatra commented on src/components/App/App.tsx
Можно лучше: так как вы все равно берете весь `burgerIngredient` тут, то 16, 17, 20 строки можно обьеденить деструкторизацией

2022-06-14 15:21 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +  const ingredientsHeader = document.getElementById('ingredients')!;
Можно лучше: вместо использования оператора `!` лучше проверить `el instanceof HTMLDivElement`

2022-06-14 15:23 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +    setCurrentTab(e);
Можно лучше: не используйте типы `any` это является плохой практикой так как ломает все попытки ts вам помочь. В будущих спринтах вы подробнее изучите как обращаться с ts, а пока можете писать на js в этом ничего плохого нет

2022-06-14 15:24 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +  };
Можно лучше: будет круто добавить `{behavior: "smooth"}` в `.scrollIntoView()`

2022-06-14 15:25 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +  const ingredients = useSelector((store: any) => store.burgerIngredients.ingredients);
Можно лучше: `"bread"` не является существующей вкладкой, мне кажется, что лучше было бы начальное состояние поставить на `"buns"`

2022-06-14 15:29 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +  const handleChangeTab = (e: any, type: any) => {
Надо исправить: `e` и `type` передают одно и то же в функцию, стоит убрать `type`

2022-06-14 15:30 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +    setCurrentTab(e);
Можно лучше: мне кажется, что элемент на id лучше брать тут, а не в теле функции

2022-06-14 15:38 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +          })}
Надо исправить: Не указан аттрибут key

2022-06-14 15:39 UTC, kyzinatra commented on src/components/ConstructorItem/ConstructorItem.tsx
> +        <ConstructorElement
Надо исправить: Драг также обязательно должен работать при клики на `DragIcon`

2022-06-14 15:40 UTC, kyzinatra commented on src/components/ConstructorItem/ConstructorItem.tsx
> +      <DragIcon type="primary" />
Надо исправить: тут уже `key` указывать не нужно

2022-06-14 15:42 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>        </ul>
Надо исправить: не стоит использовать в кажестве ключа индекс массива. Так как это не надежный способ обновлять компоненты. Лучше при добавлении ингредениета в конструктор генерировать уникальный id с помощью `uid` или `nanoid` а потом использовать его тут как `key`, также по нему удобно производить удаление

2022-06-14 15:47 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const { isBuns, constructorIngredients } = useSelector((store: any) => store.constructorOfOrder);
Надо исправить: `data` всегда содержить все ингредиеты, а не те, которые в конструкторе

2022-06-14 15:47 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>    };
Надо исправить: Булка должна передаваться в запрос с 2 сторон

2022-06-14 15:50 UTC, kyzinatra commented on src/components/BurgerIngredient/BurgerIngredient.tsx
>        </div>
Надо исправить: если `count === 0`, то не стоит рендерить его, как в дизайне

2022-06-14 15:54 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Не используйте приставку `get`
- После неудачного запроса стоит очищать состояние модального окна
- `e` и `type` передают одно и то же в функцию, стоит убрать `type`
- Изменить указание аттрибута `key` для конструктора
- Драг также обязательно должен работать при клики на DragIcon
- В запрос булки должны передаваться с 2 сторон
- Сейчас в запрос не передаются id ингредиентов конструктора
- убирать счетчик при `count === 0`

Можно лучше:

- Файл с контекстом лучше удалить так как вы его более не используете
- Стоит разбить отдельные редьюсеры в разные файлы
- если не используете @reduxjs/toolkit, то лучше удалить его из зависимостей
- Чтобы devtools не подключались в продакшене стоит проверять process.env.NODE_ENV === "devolopment"


Что понравилось:

- Хорошая композиция компонентов
- В целом DnD реализован очень хорошо

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-06-15 17:24 UTC, tyumen-777 commented on src/services/actions/index.ts
> +          type: GET_ORDER_FAILED,
Честно, не совсем понял суть замечания

2022-06-15 17:33 UTC, kyzinatra commented on src/services/actions/index.ts
> +          type: GET_ORDER_FAILED,
Если в запросе произошла какая-то ошибка, то стоит очистить состояние модальных окон (номер заказа), Чтобы пользователь не мог увидеть старый номер

2022-06-15 17:34 UTC, tyumen-777 commented on src/services/actions/index.ts
> +          type: GET_ORDER_FAILED,
Кажется понял. Спасибо!

2022-06-15 18:41 UTC, tyumen-777 commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +  const ingredientsHeader = document.getElementById('ingredients')!;
А можно пример? Если не затруднит

2022-06-15 19:15 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +  const ingredientsHeader = document.getElementById('ingredients')!;
Чтобы не было ошибки саму константу я бы объявил уже в функции где она нужна, используя входящий тип

```js
(type) =>{
const el = document.getElementById(type) 
if (!(el  instanceof HTMLDivElement)) return
... 
}
```

2022-06-15 19:18 UTC, tyumen-777 commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +  const ingredientsHeader = document.getElementById('ingredients')!;
Спасибо!

2022-06-16 18:57 UTC, kyzinatra commented
Отличная работа! Вы прекрасно потрудились. Работа принята, успехов в дальнейшем обучении

2022-06-22 13:49 UTC, merged